---
version: 2
project_name: cascader
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    dir: ./cmd
dockers:
  - image_templates:
      - ghcr.io/thurgauerkb/cascader:latest
      - ghcr.io/thurgauerkb/cascader:{{ .Tag }}
    use: buildx
    dockerfile: Dockerfile
    extra_files:
      - go.mod
      - go.sum
      - cmd/
      - internal/
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/thurgauerkb/cascader
      - --label=org.opencontainers.image.source=https://github.com/thurgauerkb/cascader
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses="GNU General Public License v3.0"
docker_manifests:
  - name_template: ghcr.io/thurgauerkb/cascader:{{ .Tag }}
    image_templates:
      - ghcr.io/thurgauerkb/cascader:{{ .Tag }}
      - ghcr.io/thurgauerkb/cascader:latest
