---
apiVersion: v1
kind: Service
metadata:
  name: cascader-metrics
  namespace: cascader-system
  labels:
    app.kubernetes.io/name: cascader
    app.kubernetes.io/component: controller
spec:
  ports:
    - name: metrics
      port: 8443
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/name: cascader
    app.kubernetes.io/component: controller
