---
apiVersion: v1
kind: Namespace
metadata:
  name: cascader-system
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: cascader
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cascader
  namespace: cascader-system
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: cascader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cascader-leader-election
  namespace: cascader-system
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: cascader
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cascader-manager
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - daemonsets
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cascader-metrics-auth
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cascader-leader-election
  namespace: cascader-system
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: cascader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cascader-leader-election
subjects:
  - kind: ServiceAccount
    name: cascader
    namespace: cascader-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cascader-manager
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: cascader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cascader-manager
subjects:
  - kind: ServiceAccount
    name: cascader
    namespace: cascader-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cascader-metrics-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cascader-metrics-auth
subjects:
  - kind: ServiceAccount
    name: cascader
    namespace: cascader-system
---
apiVersion: v1
kind: Service
metadata:
  name: cascader-metrics
  namespace: cascader-system
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: cascader
spec:
  ports:
    - name: metrics
      port: 8443
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: cascader
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: cascader
  name: cascader
  namespace: cascader-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: cascader
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: cascader
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: cascader
    spec:
      containers:
        - name: cascader
          image: ghcr.io/thurgauerkb/cascader:v0.2.5
          ports:
            - name: metrics
              containerPort: 8443
              protocol: TCP
            - name: probes
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: probes
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: probes
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      securityContext:
        runAsNonRoot: true
      serviceAccountName: cascader
      terminationGracePeriodSeconds: 10
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cascader-alerts
  namespace: cascader-system
spec:
  groups:
    - name: CascaderAlerts
      rules:
        - alert: CascaderCycleDetected
          annotations:
            description: |
              A dependency cycle has been detected in the Cascader controller.
              Namespace: {{ $labels.namespace }}, Name: {{ $labels.name }}, Resource Kind: {{ $labels.resource_kind }}.
              Please check the corresponding Kubernetes Event for detailed cycle path information.
            summary: Dependency Cycle Detected in {{ $labels.namespace }}/{{ $labels.name }}
          expr: cascader_dependency_cycles_detected > 0
          for: 1m
          labels:
            severity: critical

        - alert: CascaderHighRestartRate
          annotations:
            description: |
              Cascader has triggered more than 5 restarts for workload {{ $labels.namespace }}/{{ $labels.name }} (kind: {{ $labels.resource_kind }}) in the last 5 minutes.
              This may indicate a misconfiguration or unstable rollout.
            summary: High restart rate detected for {{ $labels.namespace }}/{{ $labels.name }}
          expr: increase(cascader_restarts_performed_total[5m]) > 5
          for: 2m
          labels:
            severity: warning
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: cascader
  name: cascader-metrics-monitor
  namespace: cascader-system
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      path: /metrics
      port: metrics
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: cascader
