---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/clusterrole-cascader.yaml
  - manifests/clusterrolebinding-cascader.yaml
  - manifests/deployment.yaml
  - manifests/leader-election-role.yaml
  - manifests/leader-election-rolebinding.yaml
  - manifests/metrics-auth-clusterrole.yaml
  - manifests/metrics-auth-rolebinding.yaml
  - manifests/metrics-service.yaml
  - manifests/metrics-servicemonitor.yaml
  - manifests/namespace.yaml
  - manifests/prometheusrule.yaml
  - manifests/serviceaccount-cascader.yaml
