---
name: Unit Tests

on:
  workflow_dispatch:
  workflow_call:

env:
  KUBERNETES_VERSION: "1.32.0"

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: Install Dependencies
        run: |
          make download

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v${{ env.KUBERNETES_VERSION }}

      - name: Export kubeconfig
        run: |
          mkdir -p "$HOME/.kube"
          kind get kubeconfig --name cascader-test > "$HOME/.kube/config"
          echo "KUBECONFIG=$HOME/.kube/config" >> "$GITHUB_ENV"

      - name: Show context
        run: |
          echo "KUBECONFIG=$KUBECONFIG"
          kubectl cluster-info
          kubectl get nodes -o wide

      - name: Set up Kind Cluster
        run: |
          make kind

      - name: Export kubeconfig
        run: |
          mkdir -p "$HOME/.kube"
          kind get kubeconfig --name cascader-test > "$HOME/.kube/config"
          echo "KUBECONFIG=$HOME/.kube/config" >> "$GITHUB_ENV"

      - name: Show context
        run: |
          echo "KUBECONFIG=$KUBECONFIG"
          kubectl cluster-info
          kubectl get nodes -o wide

      - name: Run Unit Tests
        run: |
          make test

      - name: Run E2E Tests
        run: |
          make e2e
